steps:
  - uses: actions/checkout@master
  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '3.1.100' # SDK Version to use.
    env:
      DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
  - run: dotnet restore
  - run: dotnet build -o out