name: Code Complies

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
      - run: dotnet restore
      - run: dotnet build -o out
      - run: dotnet test
